name: Build and Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Setup zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.16.0

      - name: Run build
        run: node build.js

      - name: Generate tag
        id: tag
        run: |
          VERSION=$(grep -oE "version:[[:space:]]*'[^']+'" quickjs/meson.build | sed -E "s/.*'([^']+)'/\1/")
          TIMESTAMP=$(TZ=Asia/Shanghai date +"%Y%m%d%H%M%S")

          TAG="v${VERSION}-${TIMESTAMP}"

          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Zip lib directory
        run: |
          cd lib
          zip -r ../quickjs.zip .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: quickjs ${{ steps.tag.outputs.version }}
          files: quickjs.zip
          body: quickjs ${{ steps.tag.outputs.version }}